on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install dependencies
              uses: actions/npm@master
              with:
                args: install
            - name: Build
              uses: actions/npm@master
              with:
                args: build
            - name: Make stable release to npm
              uses: epeli/npm-release@v1
              with:
                  type: stable
                  token: ${{ secrets.NPM_AUTH_TOKEN }}
